<ADSWorkspace Revision="51" Version="100">
    <Workspace Name="">
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="efi_hf-prakt_lib" />
        <Log Name="search_history.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Layer_Preference Name="efi_hf-prakt_lib.layerprf" />
        <Log Name="netlist.log" />
        <Layer_Preference Name="ads_schematic_layers.layerprf" />
        <ConfigFile Name="dds.cfg" />
        <Preferences Name="efi_hf-prakt_lib_lay.prf" />
        <Folder Name="components">
            <Cell Name="efi_hf-prakt_lib:C_10pF_0805" />
            <Cell Name="efi_hf-prakt_lib:C_100nF_0805" />
            <Cell Name="efi_hf-prakt_lib:R_10Ohm_1206" />
            <Cell Name="efi_hf-prakt_lib:BFP420_S2P_2V55M0" />
        </Folder>
        <Folder Name="designs">
            <Cell Name="efi_hf-prakt_lib:Abblockkondensator" />
            <Data_Display Name="Abblockkondensator.dds" />
            <Cell Name="efi_hf-prakt_lib:DC-Beschaltung" />
            <Data_Display Name="DC-Beschaltung.dds" />
            <Cell Name="efi_hf-prakt_lib:Emitterbeschaltung" />
            <Data_Display Name="Emitterbeschaltung.dds" />
            <Data_Display Name="Koppelkondensator.dds" />
            <Cell Name="efi_hf-prakt_lib:Koppelkondensator" />
            <Cell Name="efi_hf-prakt_lib:Bandsperre" />
        </Folder>
        <Preferences Name="ads_rflib_lay.prf" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Dataset Name="Abblockkondensator.ds" />
        <Dataset Name="DC_Beschaltung.ds" />
        <Dataset Name="Emitterbeschaltung.ds" />
        <Dataset Name="Koppelkondensator.ds" />
        <Data_Files Name="2P2V55M0_1998.S2P" />
        <Data_Files Name="2p2V55M0_2009.s2p" />
        <Data_Files Name="Abblockkondensator.ds" />
        <Data_Files Name="DC_Beschaltung.ds" />
        <Data_Files Name="Emitterbeschaltung.ds" />
        <Data_Files Name="Emitterbeschaltung_data\logFile.txt" />
        <Data_Files Name="Koppelkondensator.ds" />
        <Data_Files Name="SimLog\Abblockkondensator.log" />
        <Data_Files Name="SimLog\DC-Beschaltung.log" />
        <Data_Files Name="SimLog\Emitterbeschaltung.log" />
        <Data_Files Name="SimLog\Koppelkondensator.log" />
        <Library Name="ads_builtin" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_quantum" />
        <Library Name="Simulation_Sequencing" />
    </Workspace>
</ADSWorkspace>
